import * as game from './game.js';
import {hostRoom,joinRoom,normalizeCode} from './room.js';
import {createResumeToken,loadPlayerSession,savePlayerSession} from './storage.js';
const $=id=>document.getElementById(id), screens=['home','lobby','question','reveal','over']; let transport,state,myId,isHost=false,hostRoomState;
const show=s=>screens.forEach(x=>$(`screen-${x}`).classList.toggle('hidden',x!==s));
const me=()=>state?.players?.find(p=>p.id===myId); const call=(names,...args)=>{for(const n of names)if(typeof game[n]==='function')return game[n](...args);return null};
function invite(code){const url=`${location.origin}${location.pathname}?room=${code}`;$('room-invite-url').textContent=url;$('room-qr').replaceChildren();if(typeof qrcode==='function'){const qr=qrcode(0,'M');qr.addData(url);qr.make();$('room-qr').innerHTML=qr.createSvgTag({cellSize:3,margin:1})}return url}
function publish(){const publicState=call(['toPublicState','publicState'],hostRoomState,myId)||hostRoomState;state=publicState;transport?.broadcast('state',publicState);render()}
function hostMessage(id,event,payload){let r;if(event==='join'){r=payload.resumeToken?game.rejoinPlayer(hostRoomState,id,payload.resumeToken):{error:'No saved seat found'};if(r?.error)r=game.addPlayer(hostRoomState,id,payload.name,payload.resumeToken)}else if(event==='proposePair')r=game.proposePair(hostRoomState,id,payload.targetId);else if(event==='start')r=game.startGame(hostRoomState,id,payload);else if(event==='submitResponse')r=game.submitResponse(hostRoomState,id,payload.response);else if(event==='next'){game.resolveQuestion(hostRoomState);r=game.advance(hostRoomState)}else if(event==='rematch')r=game.rematch(hostRoomState,id,true);if(r?.error)toast(r.error);publish();return {ok:!r?.error,state:game.publicState(hostRoomState)}}
function hostClose(id){if(hostRoomState)game.removePlayer(hostRoomState,id);publish()}
async function create(){try{isHost=true;const name=$('name-input').value.trim()||'Host';transport=await hostRoom({onMessage:hostMessage,onPeerClose:hostClose,onError:e=>toast(e)});myId='host';hostRoomState=game.createRoom(transport.code,myId);if(!$('display-checkbox').checked)game.addPlayer(hostRoomState,myId,name);state=game.publicState(hostRoomState);localStorage.setItem('partyofTwoLast',transport.code);render()}catch(e){$('home-error').textContent=e.message}}
async function join(){try{isHost=false;const code=normalizeCode($('code-input').value);if(code.length!==4)throw Error('Enter the four-letter room code.');const saved=loadPlayerSession(code);const resumeToken=saved?.resumeToken||createResumeToken();transport=await joinRoom(code,{onPush:(e,p)=>{if(e==='state'){state=p;render()}},onClose:e=>toast(e)});myId=transport.id;const result=await transport.send('join',{name:$('name-input').value.trim()||saved?.name||'Player',resumeToken});savePlayerSession(code,{resumeToken,name:$('name-input').value.trim()||saved?.name||'Player'});state=result?.state||state;render()}catch(e){$('home-error').textContent=e.message}}
function render(){if(!state)return;const phase=state.phase||'lobby';show(phase==='lobby'||phase==='pairing'?'lobby':phase);if(phase==='lobby'||phase==='pairing')renderLobby();if(phase==='question')renderQuestion();if(phase==='reveal')renderReveal();if(phase==='over')renderOver()}
function renderLobby(){ $('lobby-code').textContent=state.code||'----';invite(state.code);const players=state.players||[];$('lobby-players').replaceChildren(...players.map(p=>{const row=document.createElement('div');row.className='leader-row';row.innerHTML=`<span class="leader-rank">${p.pairId?'🤝':'?'}</span><span class="leader-name"></span><span class="leader-score">${p.pairId||'Unpaired'}</span>`;row.querySelector('.leader-name').textContent=`${p.name}${p.connected===false?' · offline':''}`;return row}));const self=me();$('pairing-controls').classList.toggle('hidden',!self||phaseNotPairing());const buttons=$('pair-buttons');buttons.replaceChildren(...players.filter(p=>p.id!==myId&&!p.pairId).map(p=>{const b=document.createElement('button');b.className='choice';b.textContent=`Pair with ${p.name}`;b.onclick=()=>act('proposePair',{targetId:p.id});return b}));$('host-settings').classList.toggle('hidden',!isHost);$('start-btn').classList.toggle('hidden',!isHost);$('start-btn').disabled=players.length<2||players.length%2===1||players.some(p=>!p.pairId);$('pair-status').textContent=`${players.length} players · ${players.length%2?'Need an even number · ':''}${players.filter(p=>!p.pairId).length} unpaired`;}
function phaseNotPairing(){return state.phase!=='pairing'&&state.phase!=='lobby'}
function renderQuestion(){const q=state.current||state.currentQuestion||{};$('question-progress').textContent=`Question ${(state.qIndex||0)+1}`;$('question-text').textContent=q.prompt||q.question||'Your pair is up!';$('round-name').textContent=q.round||q.mode||'Pair challenge';$('score-pill').textContent=me()?.score!=null?`${me().score} pts`:'Host';const form=$('answer-form');form.replaceChildren();if(me()){const input=document.createElement('input');input.placeholder='Your private answer';const b=document.createElement('button');b.className='btn btn-primary';b.textContent='Lock answer';b.onclick=()=>act('submitResponse',{response:input.value});form.append(input,b)}$('question-players').textContent=(state.players||[]).map(p=>`${p.name}${p.pairId?' 🤝':''}`).join(' · ')}
function renderReveal(){const r=state.lastResult||{};$('reveal-question').textContent=r.prompt||'';$('reveal-answer').textContent=r.answer||r.correctAnswer||'—';$('reveal-leaderboard').replaceChildren(...pairRows());$('next-btn').classList.toggle('hidden',!isHost);$('next-btn').onclick=()=>act('next')}
function pairRows(){return (state.pairs||[]).slice().sort((a,b)=>(b.score||0)-(a.score||0)).map(p=>{const d=document.createElement('div');d.className='leader-row';d.innerHTML=`<span class="leader-rank">🤝</span><span class="leader-name"></span><span class="leader-score">${p.score||0} pts</span>`;d.querySelector('.leader-name').textContent=p.name||p.members?.map(id=>state.players.find(x=>x.id===id)?.name).join(' + ')||'Pair';return d})}
function renderOver(){$('over-leaderboard').replaceChildren(...pairRows());const best=Math.max(...(state.pairs||[]).map(p=>p.score||0),0);$('over-winners').textContent=(state.pairs||[]).filter(p=>p.score===best).map(p=>p.name).join(' & ');$('rematch-btn').classList.toggle('hidden',!isHost);$('rematch-btn').onclick=()=>act('rematch')}
async function act(type,payload={}){if(isHost){const r=hostMessage(myId,type,payload);state=r.state||state;render()}else{const r=await transport.send(type,payload);if(r?.state){state=r.state;render()}}}
function toast(m){$('toast').textContent=m;$('toast').classList.remove('hidden');setTimeout(()=>$('toast').classList.add('hidden'),2500)}
$('create-btn').onclick=create;$('join-btn').onclick=join;$('code-input').oninput=e=>e.target.value=normalizeCode(e.target.value);$('copy-link-btn').onclick=()=>navigator.clipboard?.writeText(invite(state.code)).then(()=>toast('Invite link copied'));
$('start-btn').onclick=()=>act('start',{questionsPerRound:Number($('questions-select').value),timerSeconds:Number($('timer-select').value)});
const prefill=new URLSearchParams(location.search).get('room');if(prefill)$('code-input').value=normalizeCode(prefill);
