import * as game from './game.js';
import {hostRoom,joinRoom,normalizeCode} from './room.js';
import {createResumeToken,loadPlayerSession,savePlayerSession,loadUsedQuestionIds,markQuestionsUsed} from './storage.js';
const $=id=>document.getElementById(id), screens=['home','lobby','question','reveal','over']; let transport,state,myId,isHost=false,hostRoomState; const answerDrafts=new Map();
const show=s=>screens.forEach(x=>$(`screen-${x}`).classList.toggle('hidden',x!==s));
const me=()=>state?.players?.find(p=>p.id===myId); const call=(names,...args)=>{for(const n of names)if(typeof game[n]==='function')return game[n](...args);return null};
function invite(code){const url=`${location.origin}${location.pathname}?room=${code}`;$('room-invite-url').textContent=url;$('room-qr').replaceChildren();if(typeof qrcode==='function'){const qr=qrcode(0,'M');qr.addData(url);qr.make();$('room-qr').innerHTML=qr.createSvgTag({cellSize:3,margin:1})}return url}
function publish(){const publicState=call(['toPublicState','publicState'],hostRoomState,myId)||hostRoomState;state=publicState;transport?.broadcast('state',publicState);render()}
function hostMessage(id,event,payload){let r;if(event==='join'){r=payload.resumeToken?game.rejoinPlayer(hostRoomState,id,payload.resumeToken):{error:'No saved seat found'};if(r?.error)r=game.addPlayer(hostRoomState,id,payload.name,payload.resumeToken)}else if(event==='proposePair')r=game.proposePair(hostRoomState,id,payload.targetId);else if(event==='start'){r=game.startGame(hostRoomState,id,{...payload,usedIds:loadUsedQuestionIds()});if(!r?.error)markQuestionsUsed(hostRoomState.deck.map(q=>q.id))}else if(event==='submitResponse'){r=game.submitResponse(hostRoomState,id,payload.response);if(!r?.error&&game.allPlayersSubmitted(hostRoomState))game.resolveQuestion(hostRoomState)}else if(event==='next'){game.resolveQuestion(hostRoomState);r=game.advance(hostRoomState)}else if(event==='rematch')r=game.rematch(hostRoomState,id,true);if(r?.error)toast(r.error);publish();return {ok:!r?.error,state:game.publicState(hostRoomState)}}
function hostClose(id){if(hostRoomState)game.removePlayer(hostRoomState,id);publish()}
async function create(){try{isHost=true;const name=$('name-input').value.trim()||'Host';transport=await hostRoom({onMessage:hostMessage,onPeerClose:hostClose,onError:e=>toast(e)});myId='host';hostRoomState=game.createRoom(transport.code,myId);if(!$('display-checkbox').checked)game.addPlayer(hostRoomState,myId,name);state=game.publicState(hostRoomState);localStorage.setItem('partyofTwoLast',transport.code);render()}catch(e){$('home-error').textContent=e.message}}
async function join(){try{isHost=false;const code=normalizeCode($('code-input').value);if(code.length!==4)throw Error('Enter the four-letter room code.');const saved=loadPlayerSession(code);const resumeToken=saved?.resumeToken||createResumeToken();transport=await joinRoom(code,{onPush:(e,p)=>{if(e==='state'){state=p;render()}},onClose:e=>toast(e)});myId=transport.id;const result=await transport.send('join',{name:$('name-input').value.trim()||saved?.name||'Player',resumeToken});savePlayerSession(code,{resumeToken,name:$('name-input').value.trim()||saved?.name||'Player'});state=result?.state||state;render()}catch(e){$('home-error').textContent=e.message}}
function render(){if(!state)return;const phase=state.phase||'lobby';show(phase==='lobby'||phase==='pairing'?'lobby':phase);if(phase==='lobby'||phase==='pairing')renderLobby();if(phase==='question')renderQuestion();if(phase==='reveal')renderReveal();if(phase==='over')renderOver()}
function renderLobby(){ $('lobby-code').textContent=state.code||'----';invite(state.code);const players=state.players||[];$('lobby-players').replaceChildren(...players.map(p=>{const row=document.createElement('div');row.className='leader-row';row.innerHTML=`<span class="leader-rank">${p.pairId?'🤝':'?'}</span><span class="leader-name"></span><span class="leader-score">${p.pairId||'Unpaired'}</span>`;row.querySelector('.leader-name').textContent=`${p.name}${p.connected===false?' · offline':''}`;return row}));const self=me();$('pairing-controls').classList.toggle('hidden',!self||phaseNotPairing());const buttons=$('pair-buttons');buttons.replaceChildren(...players.filter(p=>p.id!==myId&&!p.pairId).map(p=>{const b=document.createElement('button');b.className='choice';b.textContent=`Pair with ${p.name}`;b.onclick=()=>act('proposePair',{targetId:p.id});return b}));$('host-settings').classList.toggle('hidden',!isHost);$('start-btn').classList.toggle('hidden',!isHost);$('start-btn').disabled=players.length<2||players.length%2===1||players.some(p=>!p.pairId);$('pair-status').textContent=`${players.length} players · ${players.length%2?'Need an even number · ':''}${players.filter(p=>!p.pairId).length} unpaired`;}
function phaseNotPairing(){return state.phase!=='pairing'&&state.phase!=='lobby'}
// Every submission (including a partner's, or anyone else's in the room)
// re-broadcasts state and re-renders this screen for everyone still
// waiting to answer. Rebuilding the <input>/<button> from scratch on
// every one of those renders -- as this used to -- tore out whichever
// player was mid-keystroke: a fresh DOM node has no focus, and on mobile
// that silently dismisses the on-screen keyboard out from under them.
// Reuse the existing nodes across renders; only rebuild when the
// question itself actually changes.
function renderQuestion(){const q=state.current||state.currentQuestion||{};$('question-progress').textContent=`Question ${(state.qIndex||0)+1}`;$('question-text').textContent=q.prompt||q.question||'Your pair is up!';$('round-name').textContent=q.round||q.mode||'Pair challenge';$('score-pill').textContent=me()?.score!=null?`${me().score} pts`:'Host';const self=me();const pair=self?.pairId&&state.pairs?.find(p=>p.id===self.pairId);const partner=pair?.members?.map(id=>state.players.find(p=>p.id===id)).find(p=>p&&p.id!==myId);const status=partner?`You: ${self.submitted?'submitted':'thinking'} · ${partner.name}: ${partner.submitted?'submitted':'thinking'}`:self?`You: ${self.submitted?'submitted':'thinking'}`:'';const form=$('answer-form');const key=q.id||`question-${state.qIndex||0}`;if(self){let input=form.querySelector('input'),btn=form.querySelector('button'),note=form.querySelector('.answer-status');if(form.dataset.questionKey!==key||!input){form.replaceChildren();form.dataset.questionKey=key;input=document.createElement('input');input.placeholder='Your private answer';input.value=answerDrafts.get(key)||'';input.setAttribute('aria-label','Your answer');input.oninput=()=>answerDrafts.set(key,input.value);btn=document.createElement('button');btn.className='btn btn-primary';btn.onclick=()=>{answerDrafts.set(key,input.value);act('submitResponse',{response:input.value})};note=document.createElement('small');note.className='answer-status';form.append(input,btn,note)}input.disabled=Boolean(self.submitted);btn.disabled=Boolean(self.submitted);btn.textContent=self.submitted?'Submitted':'Lock answer';note.textContent=status}else{form.replaceChildren();delete form.dataset.questionKey}$('question-players').textContent=(state.players||[]).map(p=>`${p.name}${p.pairId?' 🤝':''}${p.submitted?' ✓':''}`).join(' · ');paintTimer()}
// Both roles repaint their own countdown locally from the shared
// startedAt + timerSeconds deadline (no per-frame network traffic); only
// the Host's tick loop below is allowed to actually force a resolve.
function paintTimer(){const timerEl=$('question-timer');const total=(state.settings?.timerSeconds||0)*1000;if(!total||state.phase!=='question'){timerEl.classList.add('hidden');return}timerEl.classList.remove('hidden');const startedAt=state.current?.startedAt||Date.now();const left=Math.max(0,startedAt+total-Date.now());$('question-timer-fill').style.transform=`scaleX(${(left/total).toFixed(4)})`;$('question-timer-label').textContent=`${Math.ceil(left/1000)}s`;timerEl.classList.toggle('danger',left>0&&left<=5000)}
function renderReveal(){const r=state.lastResult||{};$('reveal-question').textContent=r.prompt||'';$('reveal-answer').textContent=r.answer||r.correctAnswer||'—';$('reveal-leaderboard').replaceChildren(...pairRows());$('next-btn').classList.toggle('hidden',!isHost);$('next-btn').onclick=()=>act('next')}
function pairRows(){return (state.pairs||[]).slice().sort((a,b)=>(b.score||0)-(a.score||0)).map(p=>{const d=document.createElement('div');d.className='leader-row';d.innerHTML=`<span class="leader-rank">🤝</span><span class="leader-name"></span><span class="leader-score">${p.score||0} pts</span>`;d.querySelector('.leader-name').textContent=p.name||p.members?.map(id=>state.players.find(x=>x.id===id)?.name).join(' + ')||'Pair';return d})}
function renderOver(){$('over-leaderboard').replaceChildren(...pairRows());const best=Math.max(...(state.pairs||[]).map(p=>p.score||0),0);$('over-winners').textContent=(state.pairs||[]).filter(p=>p.score===best).map(p=>p.name).join(' & ');$('rematch-btn').classList.toggle('hidden',!isHost);$('rematch-btn').onclick=()=>act('rematch')}
async function act(type,payload={}){if(isHost){const r=hostMessage(myId,type,payload);state=r.state||state;render()}else{const r=await transport.send(type,payload);if(r?.state){state=r.state;render()}}}
function toast(m){$('toast').textContent=m;$('toast').classList.remove('hidden');setTimeout(()=>$('toast').classList.add('hidden'),2500)}
// Repaints the countdown every 250ms on whichever role is active (state
// itself only changes on a broadcast, so without this the timer would
// only visibly move when someone else submits). Only the Host's own
// clock may actually force a resolve when time runs out -- previously
// nothing ever did, so a timer setting was collected at setup but never
// enforced or even displayed.
setInterval(()=>{if(state?.phase==='question')paintTimer();if(isHost&&hostRoomState&&game.questionTimerExpired(hostRoomState)){game.resolveQuestion(hostRoomState);publish()}},250);
$('create-btn').onclick=create;$('join-btn').onclick=join;$('code-input').oninput=e=>e.target.value=normalizeCode(e.target.value);$('copy-link-btn').onclick=()=>navigator.clipboard?.writeText(invite(state.code)).then(()=>toast('Invite link copied'));
$('start-btn').onclick=()=>act('start',{questionsPerRound:Number($('questions-select').value),timerSeconds:Number($('timer-select').value)});
const prefill=new URLSearchParams(location.search).get('room');if(prefill)$('code-input').value=normalizeCode(prefill);
